### PR TITLE
global reworking this module fix bugs and introduce consistent code-style

### LINKED ISSUE #101: use eslint over jshint
looks like there is some static code analysis in place. however, several code styles can not be enforced with jshint.
I suggest to move the project to using eslint with a well-known configuration (e.g. [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base)).

### PR DESCRIPTION
**Pull request by benkroeger**
Sorry for this overwhelming pull-request. I've been playing around with this module for a while and found a couple of things that didn't quite work as expected. Furthermore I found myself reading a different coding style whenever I opened a new file.
In order to better understand what is happening under the hood, I reformatted the code and replaced jshint with eslint, enforcing a slightly augmented version of airbnb's code-style.
Also, since the supported engine (according to `package.json`) was `>=4.0.1` anyways, I switched to more convenient ES6 syntax in many places.

Also, this fixes #101 #102 from the issues list.

Additionally, I fixed issues that weren't reported before like: 
* wrong logical operations on detection of `authenticate` request type in `OIDCStrategy`
* improve performance for `PEM` utils dramatically
* avoid using `for ... in ...` as object property iterator
* higher level of code reusability for `OIDCStrategy`

There are still a couple of things in the code that don't quite work as they seem to have been intended - that's purely due to the nature of async programming. I'll probably open more issues for those as well

### CODE REVIEW

**Comment by benkroeger** [comment]
@brandwe can I drag your attention to this?

**Comment by brandwe** [comment]
Attention grabbed. Thank you so much for your contribution. Can you fix the Travis test? If it passes I have no problem taking this.

**Comment by benkroeger** [comment]
@brandwe only travis tests on Node versions < 4.0.0 are failing. According to your `package.json`, the node engine required for this module is `>= ~4.0.1`. I was wondering anyway why you would have travis tests for unsupported versions.
Since I wrote all the code in ES6, it will not work on versions < 4.0.0.
I suggest you remove the travis checks and release a new major version of this module to indicate that there are breaking changes

**Comment by xirzec** [comment]
@benkroeger maybe do both in this PR? (Update travis.yml and bump the version)?

**Comment by benkroeger** [comment]
@brandwe @xirzec travis is reconfigured to not test on node `< 4.0.0` anymore.
I don't think I should do the version bump in my PR. That is usually done by project maintainers. You guys need to publish the new version to npmjs.com anyway.

**Comment by brandwe** [comment]
Alright. I'm ready to take this. I'll bump up to a new major version.

**Comment by xirzec** [comment]
Thanks @brandwe and @benkroeger ! I'm looking forward to updating my sites to use the new version. :tada:

**Comment by benkroeger** [comment]
thanks guys! long journey but happy now 😀

**Pull request merged**
