### PR TITLE
Fixed policyChecker bug

### PR DESCRIPTION
**Pull request by rudfoss**
Fix for the policyChecker that will never work as the pathname will never contain query parameters.

### CODE REVIEW

**Comment by rudfoss** [comment]
See a complete description of the issue here: https://github.com/AzureAD/passport-azure-ad/issues/425

**Comment by gsandorx** [comment]
Any idea on when this PR will be merged? This version of this library is certainly having issues with Azure AD B2C

**Comment by pkuczynski** [comment]
I can confirm the same. Upgrade to 4.1.0 broke our integration as well. And there is missing CHANGELOG entry for this release, so no warning :(

**Comment by ptc-bsorek** [comment]
When will this be merged?

**Comment by jurijtokarski** [comment]
When this will be merged? I need that patch for my application.

**Pull request merged**
