### PR TITLE
#341 add in basic proxy agent

### PR DESCRIPTION
**Pull request by hsimah**
I wrote this a long time ago to authenticate behind a corporate proxy. Since I periodically get pinged in my issue #341 that other people need this I am creating this PR.

I have not used this in years and I do not work in the Microsoft tech stack any more, so maybe there is a better way to do it.

### CODE REVIEW

**Comment by p-m-p** [comment]
Is this going to be merged? I am also facing this issue and am having to use a fork for client project.

**Comment by ColinRichardsonDWP** [comment]
We need to use a proxy to connect to Azure and this is the solution that we've had to patch the passport-azure-ad to resolve it.  I'd like to remove this patch, so will this (as asked already today) be merged in?

**Comment by p-m-p** [comment]
I will happily take this and update the in code documentation if needed.

**Comment by hsimah** [comment]
rebased and added the proxy option to the documentation comment

**Comment by KatharineArnold** [comment]
@hsimah  The force push required me to update to a newer version of this branch. The latest commit 0cb2df5 was not working for me, but the previous commit bb98743 is working as expected.

The error I'm getting from the latest commit is:
502 Bad Gateway: Registered endpoint failed to handle the request.

**Comment by hsimah** [comment]
@KatharineArnold I am sorry about that, let me see what I broke.

*Edit*: Should be fixed, I merged in a regression when I did the rebase. Foolish of me since I can't test these changes.

**Comment by p-m-p** [comment]
Any update on getting this merged @KatharineArnold?

**Comment by ed0906** [comment]
Would be really useful to get this merged if possible

**Comment by ed0906** [comment]
@hsimah Any chance you could resolve the conflict in the README please?

**Comment by hsimah** [comment]
merged dev into my branch (not gonna rebase and force push again)

**Comment by ed0906** [comment]
Awesome, @markwoodward23 @DaleMcNair Any chance of getting this merged?

Our team is looking to integrate with Passport and we desperately need this 👍

**Comment by hsimah** [comment]
I'd like to see this merged too! Coming up on 3 years since I first did it lol.

**Comment by ed0906** [comment]
@jennyf19 @lovemaths @DaleMcNair @markwoodward23 
Any chance of a merge? If this project has gone stale we'll have to look elsewhere. It'd be useful to know either way if possible please.

Thanks

**Comment by jennyf19** [comment]
@DarylThayil @jasonnutter can this be merged?

**Comment by ed0906** [comment]
This repository appears to have gone stale. We found an alternative way to achieve this but it involved pulling out passport-azure-ad.

See https://github.com/auth0/node-jwks-rsa
Provide the library with your proxy config and a `jwksUri` which can be found on the `.well-known` endpoint response, it goes away and fetches the public keys + caches them. It then integrates easily with common frameworks e.g. Passport/Koa/Express etc

In the end it ended up being less code than just using `passport-azure-ad` on its own 👍 
It's also still maintained :)

**Comment by p-m-p** [comment]
> This repository appears to have gone stale. We found an alternative way to achieve this but it involved pulling out passport-azure-ad.
> 
> See https://github.com/auth0/node-jwks-rsa
> Provide the library with a `jwksUri` which can be found on the `.well-known` endpoint response, it goes away and fetches the public keys + caches them. It then integrates easily with common frameworks e.g. Passport/Koa/Express etc
> 
> In the end it ended up being less code than just using `passport-azure-ad` on its own 
> It's also still maintained :)

Thanks for that, I will take a look. Such a shame that this simple change required by many of Microsoft's customers has dragged on for so long :crying_cat_face:

**Comment by ed0906** [comment]
> > This repository appears to have gone stale. We found an alternative way to achieve this but it involved pulling out passport-azure-ad.
> > See https://github.com/auth0/node-jwks-rsa
> > Provide the library with a `jwksUri` which can be found on the `.well-known` endpoint response, it goes away and fetches the public keys + caches them. It then integrates easily with common frameworks e.g. Passport/Koa/Express etc
> > In the end it ended up being less code than just using `passport-azure-ad` on its own
> > It's also still maintained :)
> 
> Thanks for that, I will take a look. Such a shame that this simple change required by many of Microsoft's customers has dragged on for so long 😿

Forgot to mention the most important bit, that library lets you configure it to use a proxy

**Comment by hsimah** [comment]
I really wanted to add Microsoft to my list of contributions lol

**Comment by jennyf19** [comment]
@jasonnutter Can this be merged?

**Comment by p-m-p** [comment]
Is it possible to get this merged please. It really has dragged on for such a long time and there is nothing I can see that would prevent it being pushed. Thanks.

**Comment by jennyf19** [comment]
I'll ping the team on this, thanks for your patience. @hsimah @p-m-p

**Comment by jennyf19** [comment]
Thanks @jasonnutter

**Comment by jasonnutter** [comment]
This is available `passport-azure-ad@4.3.0-beta.0`. Please try it out and let me know if there are any problems, thanks!

**Pull request merged**
