### PR TITLE
Fixed an invalid conditional

### PR DESCRIPTION
**Pull request by richardspence**
The conditional was to short circuit key checking but it never worked as intended

### CODE REVIEW

**Comment by polita** [comment]
@richardspence Thanks for your contribution. This is already fixed in the dev branch. If you're contributing or pulling current sources, please use the dev branch.

**Comment by richardspence** [comment]
Ok good to know.  In the current NPM package, this is not fixed.  I also can't used npm install {this git url} as a workaround.  Can you publish these changes to the NPM package, because right now the BearerStrategy is broken because of it?

**Comment by richardspence** [comment]
Also related #168

**Comment by polita** [comment]
We're working on a release in the next week or so. It'll be on npm as well.

**Comment by richardspence** [comment]
Ok sounds good.  I'm unblocked by using my own fork, but I just want to be clear, I find the NPM package as completely unusable in it's current state (note: I'm only trying to use the bearerstrategy).  You should consider expediting the release.

**Pull request closed without merging**
