### PR TITLE
Allow resource parameter, response mode, and response type options to be set

### PR DESCRIPTION
**Pull request by SLesser**
- Include the "resource" parameter when there is one...otherwise the request to get the access token will fail.

- Allow local options of response mode and response type to override the global options

### CODE REVIEW

**Comment by brandwe** [comment]
Can you explain why you are using options instead of self_.*. Those are options that are loaded by the configuration method and already passed by the config.js. Did you look at the latest (1.3.0) when making the changes?

**Comment by SLesser** [comment]
I was looking at 1.2 at that point...but isn't the config and self options set up during initialization rather than when making an authenticate call?  It seems that different post requests may want different responses (separate calls for id tokens versus access tokens).

Sent from Outlook<http://aka.ms/Ox5hz3>




On Tue, Sep 1, 2015 at 10:11 PM -0700, "Brandon Werner" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you explain why you are using options instead of self_.*. Those are options that are loaded by the configuration method and already passed by the config.js. Did you look at the latest (1.3.0) when making the changes?

-

**Comment by brandwe** [comment]
Actually, I completely changed that for 1.3.0 for B2C. Now configuration is loaded at authentication time and then cached unless changed. This is because for B2C policies have their own metadata and can be changed at runtime. We don't know what policy we'll get. So, I just cache each policy metadata as it comes by.

https://github.com/AzureAD/passport-azure-ad/blob/master/lib/passport-azure-ad/oidcstrategy.js#L554

**Comment by SLesser** [comment]
As discussed in email, this pull request is to enable the caller to specify different response types from their authenticate call while still using the same strategy object between the different calls.

**Pull request closed without merging**
