### PR TITLE
Sijliu/v3.0.0 remove

### PR DESCRIPTION
**Pull request by lovemaths**
(1) remove examples, update readme
(2) remove saml and wsfed, and related tests
(3) remove _shouldLoadUserProfile, simplify code

### CODE REVIEW

**Comment by polita** [comment]
Where are the examples going? IOW, where do I go to get them now?

**Comment by lovemaths** [comment]
@polita I updated the readme, which has the links. They are in the second commit:
https://github.com/AzureAD/passport-azure-ad/pull/181/commits/4a74a7e56ccf351dd22c3c3c6b13675f5a5512b6

**Comment by polita** [comment]
@lovemaths Those look like they are paths to the full samples. What happened to the smaller example projects that were in /examples? Are they accessible somewhere?

**Comment by lovemaths** [comment]
@polita Those in the sample website and those in the /examples folders are the same ones. The sample website doesn't have the saml and wsfed examples, but since we no longer have saml and wsfed strategies in v3.0.0, they can see these two examples in v2.0.1.

**Comment by polita** [comment]
Great- thank you!

**Comment by lovemaths** [comment]
Removed the last commit (the _shouldLoadUserProfile change) and make it a separated PR due to merge conflicts.

**Comment by lovemaths** [comment]
@polita  is this PR ready to go?

**Comment by polita** [comment]
:shipit:

**Pull request merged**
