### PR TITLE
Support passReqToCallback option

### PR DESCRIPTION
**Pull request by apterfung**
as subject

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Is it possible to get this merged in asap?

**Comment by brandwe** [comment]
Yes I'll take a look at it tomorrow morning.

**Comment by onetom** [comment]
Much appreciated mate!

**Comment by sjmackenzie** [comment]
Much appreciated mate!

**Comment by sjmackenzie** [comment]
Per chance would you know how long it takes for this patch to get into npmjs.com as this is the last blocker for production deployment (using NixOS thus it only sees npmjs.com :-)

**Comment by brandwe** [comment]
I'll update the package as soon as I look / take the pull request :-)

**Comment by sjmackenzie** [comment]
That's perfect mate!

**Comment by apterfung** [comment]
Thanks a lot. =P

**Comment by brandwe** [comment]
Excellent. This allows you to pass req in the callback. A useful feature and supported by Passport. 

A TODO for me is to update the sample app for this and tell the developer to set `passReqToCallback: true` in their code for it to work, however it's well documented in Passport's docs so a developer should be able to find it.

Those interested in what this allows can visit [here](http://passportjs.org/guide/authorize/)

**Comment by sjmackenzie** [comment]
Hey Brandon, that's a very informative response! Thanks! (@onetom)

**Comment by brandwe** [comment]
npmjs module has been updated. Enjoy :+1:

**Comment by sjmackenzie** [comment]
\m/ The show goes on! (@apterfung)

**Comment by apterfung** [comment]
ヾ(＠⌒ー⌒＠)ノ

**Pull request merged**
