### PR TITLE
Remove waffle.io references (dead links)

### PR DESCRIPTION
**Pull request by cjancsar**
Remove references to waffle.io (as that has been dead for a long time)

### CODE REVIEW

**Comment by cjancsar** [comment]
Is this repo dead?

**Comment by jeffwilcox** [comment]
@cjancsar I hope not... I'm still using this library! Let me ask around though to see who should be maintaining this.

I wish that GitHub would assign some sort of "maintainer score" etc. to repos.

**Review by jeffwilcox — APPROVED** [review]

**Comment by jasonnutter** [comment]
@jeffwilcox MSAL.js team maintains this, apologies for the delay in responding!

**Comment by jeffwilcox** [comment]
Sweet, thank you @jasonnutter!

**Pull request merged**
