### PR TITLE
remove _shouldLoadUserProfile

### PR DESCRIPTION
**Pull request by lovemaths**
This function assumes options.skipUserProfile can be a function, this is impossible since options.skipUserProfile is read from the config file, it can only be true or false. So let's remove this dead code.

For any code like:

```
self._shouldLoadUserProfile(iss, sub, (err, load) => {
     if (err)
        err_handling_logic;
     callback_function_body;
   }
);
```

We don't need _shouldLoadUserProfile to decide if we want to load user profile, so remove the _shouldLoadUserProfile and transform it to
```
 // we don't load userinfo unless user set skipUserProfile to false
const load = (self._options.skipUserProfile === false);

callback_function_body;
```

### CODE REVIEW

**Comment by polita** [comment]
@brandwe What was the intention behind options.skipUserProfile supporting a function? Was that always dead code?

**Comment by lovemaths** [comment]
@polita That is intended to allow developer to provide their own logic of deciding if load userinfo or not. This is unnecessary, they just need to provide 'true' or 'false' for that field.

**Comment by brandwe** [comment]
It's slightly more complicated. Passport.js provides for the default User Info Endpoint flow where we grab data from that place and then populate a profile object. We don't have User Info Endpoint (yet) so instead I populate the profile object with data from the ID Token. 

However eventually we will have a User Info Endpoint so for now I kept the code in there from the forked library but pass a way to "skipUserProfile"

**Comment by polita** [comment]
Why would anyone want to skip loading the user profile? What's the scenario?

**Comment by lovemaths** [comment]
@brandwe I think v1 has userinfo endpoint but v2 doesn't.

**Comment by brandwe** [comment]
Indeed. The scenario is if the IdP doesn't have a User Info Endpoint (like us)

**Comment by lovemaths** [comment]
@brandwe @polita Our treatment of userinfo is that 
(1) we load userinfo if user set skipUserProfile false and it's v1
(2) we use id_token otherwise
(3) if user sets skipUserProfile true but it's v2, we give a warning

skipUserProfile only needs to be true or false for us, and we don't care about any other IdP's.

Please either reject this PR with a good reason or give a shipit. Thanks.

**Comment by polita** [comment]
If the only reason to skip loading the user profile is that you're in V2 where there's no endpoint, should we error if you set it to true in V1 and if you set it to false in V2? Given that it's completely dependent on whether there's a user info endpoint, why have this as a user setting at all?

**Comment by lovemaths** [comment]
@polita That makes sense, we should remove skipUserProfile from the setting, we always load userinfo from v1, and always don't load from v2. I will make the change.

**Comment by polita** [comment]
@lovemaths Thanks Sijun.

**Comment by lovemaths** [comment]
@polita Removed skipUserProfile option in the second commit.

**Comment by polita** [comment]
:shipit:

**Pull request merged**
